-- create
CREATE TABLE DEPARTMENT (
EMPLOYEE_ID INT,
NAME VARCHAR(25),
DEPARTMENT_ID VARCHAR(10),
MANAGER_ID VARCHAR(10),
SALARY DECIMAL(18,2)
);

-- insert

INSERT INTO DEPARTMENT(EMPLOYEE_ID, NAME, DEPARTMENT_ID, MANAGER_ID, SALARY)
VALUES (100, 'STEVEN KING', '90', '100', 24000);
INSERT INTO DEPARTMENT(EMPLOYEE_ID, NAME, DEPARTMENT_ID, MANAGER_ID, SALARY)
VALUES (101, 'NEENA KOCCHAR', '90', '100', 17000);
INSERT INTO DEPARTMENT(EMPLOYEE_ID, NAME, DEPARTMENT_ID, MANAGER_ID, SALARY)
VALUES (102, 'LEX DEHAAN', '90', '102', 9000);
INSERT INTO DEPARTMENT(EMPLOYEE_ID, NAME, DEPARTMENT_ID, MANAGER_ID, SALARY)
VALUES (103, 'BRUCE LEE', '60', '103', 4800);
INSERT INTO DEPARTMENT(EMPLOYEE_ID, NAME, DEPARTMENT_ID, MANAGER_ID, SALARY)
VALUES (104, 'DIANA WILLS', '60', '103', 25000);
INSERT INTO DEPARTMENT(EMPLOYEE_ID, NAME, DEPARTMENT_ID, MANAGER_ID, SALARY)
VALUES (105, 'VALLI PATOR', '50', '102', 4200);
INSERT INTO DEPARTMENT(EMPLOYEE_ID, NAME, DEPARTMENT_ID, MANAGER_ID, SALARY)
VALUES (1973, 'LUV HAMI', '60', '102', 5000);
INSERT INTO DEPARTMENT(EMPLOYEE_ID, NAME, DEPARTMENT_ID, MANAGER_ID, SALARY)
VALUES (106, 'DAVID AUSTIN', '90', '100', 6000);

-- fetch

SELECT * FROM DEPARTMENT;

SELECT DEPARTMENT_ID , COUNT(*) AS number_of_employee FROM DEPARTMENT
GROUP BY DEPARTMENT_ID;

SELECT DEPARTMENT_ID , COUNT(*) AS number_of_employee FROM DEPARTMENT
GROUP BY DEPARTMENT_ID
HAVING COUNT(*)>2

SELECT MANAGER_ID , AVG(SALARY) AS average_salary FROM DEPARTMENT
GROUP BY MANAGER_ID;